project:
  type: website
  output-dir: docs
  render:
    - index.qmd
    - slides.qmd
              
website:
  title: ""
  search: false  
  navbar:
    search: false
    title: MGMT 767 / BUSI 449
    file: index.qmd
    right:
      - text: Slides
        file: slides.qmd
      - text: Notebooks
        href: https://github.com/learn-investments/mgmt767/tree/main/notebooks
      - text: Learn Investments
        href: https://learn-investments.rice-business.org    
        
format: 
  html:
    theme: cosmo
    scss: styles.css
    link-external-newwindow: true
    
   



